;; 1.16
(define (even? n)
  (= (remainder n 2) 0))
(define (d n b a)
  (display "===")
  (newline)
  (display "n = ")
  (display n)
  (newline)
  (display "b = ")
  (display b)
  (newline)
  (display "a = ")
  (display a)
  (newline)
  (display "===")
  (newline)
  (newline))

(define (fast-expt b n)
  (define (iter b n a)
    ;;(d n b a)
    (cond ((= n 0) a)
          ((even? n) (iter (square b) (/ n 2) a))
          (else (iter b (- n 1) (* a b)))))
  (iter b n 1))

